Milestone 4
Tripple-A/React-Calculator pull request #4
Opened 2020-02-19 16:23 UTC by Tripple-A

logic folder has been added and the operate and calculate functions also appended. Upon import to App.js, the line "// eslint-disable-next-line" was added since the project requirement states Calculate should only be imported and the eslint rules forbid importing without usage.

2020-02-19 17:01 UTC, bolah2009 requested changes
Hi @Tripple-A 

Kindly check out the comments below and make changes.

#### :recycle:  Make these changes and submit another code review request. 👍🏾

#### Feel free to reach me on slack if you having issues implementing these features. :relaxed: 

Good luck with your next submission. :star2: 

Cheers
[Bola](https://bolabuari.com/)

###### PS: Note that comments tagged as `OPTIONAL` are not part of the minimum requirements to approve this PR

2020-02-19 17:01 UTC, bolah2009 commented on src/logic/Operate.js
> +      return Big(num1).mod(Big(num2));
`%` is a modifier not `mod` operator. E.g. `95% should equal to 0.95` (Hint divide by 100)

> `operate` switches `operation` and uses `plus`, `minus`, `times`, `div` and `modifier` (turning the number into a percentage based number, `e.g. 95 % == .95`) functions ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone4/performOperate.png))

2020-02-19 17:01 UTC, bolah2009 commented on src/logic/Operate.js
> +      return Big(num1).div(Big(num2));
Let's handle division by `0`

Since if `num2` is `0`, the `Big` method will throw an `Error`. Let's handle cases where `num2` is `0` differently.

2020-02-19 17:01 UTC, bolah2009 commented on package.json
> +    "big.js": "^5.2.2",
Let's use `big-js` instead of `big.js`. See https://www.npmjs.com/package/big-js

2020-02-19 17:01 UTC, bolah2009 commented on src/logic/Calculate.js
> +};
- Let's change `name` to `buttonName` to make it more meaningful
   ![image](https://user-images.githubusercontent.com/36057474/74854889-3b87f680-5340-11ea-8f88-9b93be97f060.png)
- Let's add the case where `=` is been pressed. This is when we want to call the `operate` function.
- Let's add the case where `AC` is been pressed. This is when `buttonName === AC`, all values should reset.
- Let's handle the case where `buttonName` is a number. The `calculate` function should be able to concatenate numbers
- Let's also handle cases where '.' is pressed. Note that:
   - when `next` and `total` is `undefined`, "0." should be returned
   - when `next` is defined, `.` should be appended to it
- We should return the calculator objects (`total`, `next` and `operation`)
   > `calculator data object` contains three properties: `total`, `next` and `operation` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone4/totalNextOperate.png))

2020-02-20 01:57 UTC, bellom approved these changes
## Hi @Tripple-A  :clap: 

**Great work making all the necessary corrections from the previous review.**

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit project completion form.
Good luck in the next milestone :slightly_smiling_face:_ 

Best,

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-02-20 08:22 UTC, merged